const express = require("express");
const router = express.Router();
const ManualCheck = require("../models/ManualCheck");
const WeatherData = require("../models/WeatherData");
const Report = require("../models/report");
const PDFDocument = require("pdfkit");
const path = require("path");
const fs = require("fs");

// 🧾 PDF للموظف
router.get("/:id/pdf", async (req, res) => {
  try {
    const { id } = req.params;
    const check = await ManualCheck.findById(id)
      .populate("employee", "name email")
      .populate("weatherData");

    if (!check) return res.status(404).json({ error: "Check not found" });
    const weather = check.weatherData;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=WeatherCheck_${id}.pdf`);

    const doc = new PDFDocument();
    doc.pipe(res);

    doc.fontSize(20).text("Weather Check Report", { align: "center" });
    doc.moveDown();

    doc.fontSize(12)
      .text(`Employee: ${check.employee?.name || "Unknown"}`)
      .text(`Email: ${check.employee?.email || "N/A"}`)
      .text(`Date: ${new Date(check.createdAt).toLocaleString()}`)
      .moveDown();

    doc.text("Location:");
    doc.text(`Latitude: ${weather.location.lat.toFixed(4)} | Longitude: ${weather.location.lng.toFixed(4)}`)
      .moveDown()
      .text(`Prediction: ${check.modelPrediction}`)
      .text(`Checked At: ${new Date(check.modelCheckedAt).toLocaleString()}`)
      .moveDown()
      .text("Weather Data:")
      .text(`Temperature: ${weather.temperature} °C`)
      .text(`Humidity: ${weather.humidity} %`)
      .text(`Wind Speed: ${weather.windSpeed} km/h`)
      .text(`Rainfall: ${weather.rainfall} mm`)
      .moveDown()
      .text("Fire Weather Indices:")
      .text(`FFMC: ${weather.indices.ffmc.toFixed(2)}`)
      .text(`DMC: ${weather.indices.dmc.toFixed(2)}`)
      .text(`DC: ${weather.indices.dc.toFixed(2)}`)
      .text(`ISI: ${weather.indices.isi.toFixed(2)}`)
      .text(`BUI: ${weather.indices.bui.toFixed(2)}`)
      .text(`FWI: ${weather.indices.fwi.toFixed(2)}`)
      .moveDown()
      .text("-------------------------------------------", { align: "center" })
      .text("Generated by Nuthur System", { align: "center", italic: true });

    doc.end();
  } catch (err) {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
});


router.get("/report/:id/pdf", async (req, res) => {
  try {
    const { id } = req.params;
    const report = await Report.findById(id).populate("user", "name email");
    if (!report) return res.status(404).json({ error: "Report not found" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=Volunteer_Report_${id}.pdf`);

    const doc = new PDFDocument({ margin: 40 });
    doc.pipe(res);

    doc.fontSize(20).text(" Volunteer Report Summary", { align: "center" }).moveDown();
    doc.fontSize(12)
      .text(`Volunteer Name: ${report.user?.name || "Unknown"}`)
      .text(` Email: ${report.user?.email || "N/A"}`)
      .text(` Date: ${new Date(report.createdAt).toLocaleString()}`)
      .moveDown()
      .text(` Location: ${report.location.lat.toFixed(4)}, ${report.location.lng.toFixed(4)}`)
      .text(` Description: ${report.description}`)
      .text(` Status: ${report.status}`)
      .moveDown();

    if (report.modelPrediction) doc.text(` Model Prediction: ${report.modelPrediction}`);
    if (report.modelCheckedAt)
      doc.text(` Checked At: ${new Date(report.modelCheckedAt).toLocaleString()}`);

    //  إدراج الصورة (إن وجدت)
   if (report.image) {
  const filename = report.image.split("\\").pop().split("/").pop();
  const imageUrl = `http://localhost:5000/api/reports/image/${filename}`;

  try {
    const axios = require("axios");
    const response = await axios.get(imageUrl, { responseType: "arraybuffer" });
    const imgBuffer = Buffer.from(response.data, "binary");
    doc.fontSize(16).text(" Report Image", { align: "center" });
    doc.image(imgBuffer, {
      fit: [450, 400],
      align: "center",
      valign: "center",
    });
  } catch (err) {
    console.error("⚠️ Failed to fetch image for PDF:", err.message);
    doc.moveDown();
    doc.text("⚠️ Image could not be loaded.", { align: "center", color: "red" });
  }
}

    doc.moveDown();
    doc.text("-------------------------------------------", { align: "center" });
    doc.text("Generated by Nuthur System", { align: "center", italic: true });
    doc.end();
  } catch (err) {
    console.error(" PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
});

module.exports = router;
